[package]
name = "rrwos"
version = "0.1.0"
authors = ["Katsuki Kobayashi <rare@tirasweel.org>"]
edition = "2018"

[dependencies]
volatile-register = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
